#line 1 "python.flex.cpp"

#line 3 "python.flex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 147
#define YY_END_OF_BUFFER 148
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[363] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  148,  145,  145,    3,   49,  116,    1,   15,
       18,  115,   41,   42,   11,    9,   47,   10,   50,   13,
      112,  112,   48,   51,   22,   28,   23,  119,  119,  119,
      119,   43,   44,   20,  119,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
      119,  119,   45,   19,   46,   21,    7,    5,  120,  144,
      120,  140,  147,  121,  121,  141,  122,  138,  123,  139,
      147,    6,    0,    4,   27,    0,    1,   34,   35,    0,
       12,   31,   29,   30,   52,   14,   32,  112,  113,  103,

      109,  106,  114,   16,   25,   26,   24,   17,  119,  119,
      119,  119,   37,  119,   68,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,  119,
       53,  119,   78,   79,  119,  119,  119,  119,   83,  119,
      119,  119,  119,  119,  119,  119,  119,  119,  119,   36,
        7,    8,    5,  120,  127,  126,  134,    0,  125,  128,
      129,  130,  124,  131,  132,    0,  133,    0,  121,  122,
        0,  123,    0,    0,    2,  118,  117,   40,   33,    0,
      103,  104,  105,  109,  110,  111,  106,  107,  108,  112,
      114,   39,   38,  119,  119,  119,   67,  119,  119,  119,

      119,  119,  119,  119,  119,  119,   57,   74,  119,  119,
      119,  119,  119,  119,   61,  119,  119,  119,   88,  119,
      119,  119,  119,   82,  119,  119,  119,  119,   99,   95,
       58,  119,  119,  119,  119,    7,    8,    5,  134,    0,
        0,    0,  142,  143,    0,  103,  105,    0,  109,  111,
        0,  106,  108,  114,  119,   65,   66,  119,  119,  119,
       91,  119,  119,  119,  119,  119,  101,   54,   55,  119,
      119,  119,   75,  119,  119,  119,  119,   92,  119,  119,
       84,  119,  119,  119,  119,  119,   63,  119,  134,    0,
        0,  135,  105,  111,  108,   64,  119,  119,   70,   71,

       72,  119,   96,   56,  119,  119,  119,  119,   89,  119,
      119,  119,  119,  119,  119,   85,   94,  119,   93,   62,
       87,    0,    0,  119,   69,  119,  119,  119,   59,  119,
      119,   76,   77,   80,  119,  119,   86,    0,  136,  119,
      119,   90,  119,   60,  119,  119,  119,    0,  102,  119,
       73,  119,  119,   81,    0,   97,  100,  119,    0,   98,
      137,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,    1,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       23,   23,   23,   23,   23,   24,   24,   25,   26,   27,
       28,   29,    1,    1,   30,   31,   30,   30,   30,   32,
       33,   33,   33,   33,   33,   33,   33,   34,   35,   33,
       33,   33,   33,   36,   37,   33,   33,   38,   33,   33,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   33,   53,   54,   55,   56,
       57,   58,   33,   59,   60,   61,   62,   63,   64,   65,
       66,   67,   68,   69,   70,   71,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    5,    5,    1,    1,    1,    1,    1,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    1,    7,
        1,    1,    8,    5,    5,    5,    5,    5,    5,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    1,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[393] =
    {   0,
        0,   70,   70,   74,   75,   82,   62,   69,   76,   80,
        0,    0,  588,  589,  589,   89,  559,  578,    0,  557,
      556,  571,  589,  589,   78,  554,  589,   68,  589,   79,
      102,  106,  589,  589,   73,  553,   75,    0,  536,  522,
      519,  589,  589,  549,   57,   75,   51,   46,   77,   94,
      522,  101,   67,  527,  517,  514,  528,   91,  104,   96,
       92,  519,  589,  542,  589,  589,  158,  160,    0,  589,
        0,  589,  160,    0,    0,  589,    0,  557,    0,  560,
      589,  167,  564,  172,  589,  558,    0,  589,  589,  553,
      536,  589,  589,  589,  589,  535,  589,  163,  519,  155,

      167,  205,  170,  533,  589,  589,  589,  532,    0,  505,
      502,  495,  589,  509,   52,  511,  497,  505,  491,  507,
      124,  147,  504,  111,  503,  492,  490,  487,  488,  487,
        0,  485,  481,    0,  486,  480,  484,  146,    0,  478,
      143,  476,  475,  476,  468,  475,  480,  470,  482,  589,
      206,  209,  212,    0,  589,  589,  209,    0,  589,  589,
      589,  589,  589,  589,  589,    0,  589,    0,    0,    0,
      517,    0,  520,  236,  524,  589,  589,  589,  589,  483,
      212,  482,  219,  222,  481,  235,  258,  480,  287,  248,
      252,  589,  589,  462,  473,  472,    0,  471,  462,  465,

      462,  471,  466,  453,  454,  450,    0,    0,  449,  460,
      460,  459,  462,  461,    0,  192,  459,  446,    0,  457,
      440,  443,  445,    0,  438,  437,  446,  433,    0,    0,
        0,  440,  439,  441,  437,  218,  258,  261,  262,    0,
        0,    0,  589,  589,  447,  271,  277,  446,  300,  303,
      445,  444,  443,  316,  437,  448,    0,  424,  436,  420,
        0,  427,   94,  419,  424,  425,    0,    0,    0,  417,
      420,  410,    0,  419,  419,  400,  408,    0,  392,  391,
        0,  395,  391,  379,  387,  384,    0,  383,  589,    0,
        0,  589,  306,  329,  384,    0,  357,  353,    0,    0,

        0,  312,    0,    0,  322,  313,  307,  313,    0,  310,
      311,  303,  319,  296,  315,    0,    0,  304,    0,    0,
        0,    0,    0,  300,    0,  298,  291,  293,    0,  288,
      293,    0,    0,    0,  285,  303,    0,    0,  589,  297,
      300,    0,  294,    0,  293,  277,  262,    0,    0,  249,
        0,  252,  264,    0,    0,    0,    0,  236,    0,    0,
      589,  589,  372,  380,  388,  396,  404,  412,  416,  420,
      428,  436,  444,  452,  456,  460,  464,  292,  291,  289,
      282,  281,  272,  468,  263,  261,  256,  241,  212,  198,
      131,   84

    } ;

static const flex_int16_t yy_def[393] =
    {   0,
      362,    1,  363,  363,  364,  364,  365,  365,  366,  366,
      367,  367,  362,  362,  362,  362,  362,  362,  368,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      369,  369,  362,  362,  362,  362,  362,  370,  370,  370,
      370,  362,  362,  362,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  362,  362,  362,  362,  362,  362,  371,  362,
      371,  362,  362,  372,  372,  362,  373,  362,  374,  362,
      362,  362,  362,  362,  362,  362,  368,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  369,  369,  375,

      376,  377,  369,  362,  362,  362,  362,  362,  370,  370,
      370,  370,  362,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  362,
      362,  362,  362,  371,  362,  362,  362,  378,  362,  362,
      362,  362,  362,  362,  362,  379,  362,  380,  372,  373,
      362,  374,  362,  362,  362,  362,  362,  362,  362,  369,
      375,  375,  375,  376,  376,  376,  377,  377,  377,  369,
      362,  362,  362,  370,  370,  370,  370,  370,  370,  370,

      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  362,  362,  362,  362,  381,
      382,  383,  362,  362,  375,  375,  362,  376,  376,  362,
      377,  189,  384,  362,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  362,  385,
      386,  362,  362,  362,  384,  370,  370,  370,  370,  370,

      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  370,  370,  370,
      370,  387,  388,  370,  370,  370,  370,  370,  370,  370,
      370,  370,  370,  370,  370,  370,  370,  389,  362,  370,
      370,  370,  370,  370,  370,  370,  370,  390,  370,  370,
      370,  370,  370,  370,  391,  370,  370,  370,  392,  370,
      362,    0,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362

    } ;

static const flex_int16_t yy_nxt[661] =
    {   0,
       14,   15,   16,   15,   15,   15,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   32,   32,   33,   34,   35,   36,   37,   38,
       38,   39,   38,   40,   38,   41,   38,   38,   42,   14,
       43,   44,   38,   45,   46,   47,   48,   49,   50,   51,
       38,   52,   38,   53,   54,   55,   56,   57,   58,   59,
       60,   38,   38,   61,   38,   62,   38,   63,   64,   65,
       66,   67,   70,   78,   71,   68,   70,   70,   71,   75,
       78,   72,   76,   80,   70,   72,   75,   80,  361,   76,
       82,   83,   91,  122,   84,   94,   95,  123,   96,  104,

      105,   73,  107,  108,  120,   92,   97,  121,   73,   73,
      135,  198,  114,   73,   73,   73,  115,  199,  136,   73,
      116,   73,   98,   98,   98,   98,   98,   98,   98,   98,
      124,  117,  100,  118,  141,  359,  101,  302,  142,  102,
      119,  125,  147,  148,  103,  126,  100,  127,  103,  131,
      128,  143,  129,  303,  145,  132,  133,  146,  101,  151,
      134,  152,  210,  152,  144,  153,  102,  155,   82,   83,
      211,  156,  174,  174,   83,  181,  181,   84,  205,  206,
      157,  157,  157,   98,   98,   98,   98,  184,  184,  184,
      190,  190,  190,  190,  226,  207,  158,  183,  227,  159,

      208,  223,  355,  160,  161,  103,  224,  236,  162,  186,
      237,  237,  191,  237,  237,  163,  348,  238,  164,  236,
      165,  166,  167,  237,  168,  187,  187,  187,  187,  239,
      239,  239,  181,  181,  187,  187,  187,  174,   83,  246,
      246,  174,  184,  184,  184,  339,  273,  189,  187,  187,
      187,  187,  187,  187,  183,  249,  249,  249,  274,  237,
      338,  247,  237,  237,  186,  323,  238,  322,  190,  190,
      190,  190,  254,  254,  254,  254,  292,  250,  187,  187,
      187,  187,  289,  289,  289,  291,  290,  187,  187,  187,
      103,  246,  246,  242,  191,  241,  240,  293,  293,  360,

      189,  187,  187,  187,  187,  187,  187,  252,  252,  252,
      252,  358,  357,  183,  356,  354,  252,  252,  252,  247,
      249,  249,  249,  294,  294,  294,  293,  293,  353,  253,
      252,  252,  252,  252,  252,  252,  254,  254,  254,  254,
      352,  351,  186,  350,  349,  250,  347,  346,  247,  294,
      294,  294,  345,  344,  343,  342,  341,  340,  191,  337,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  250,   69,   69,   69,   69,   69,   69,   69,   69,
       74,   74,   74,   74,   74,   74,   74,   74,   77,   77,
       77,   77,   77,   77,   77,   77,   79,   79,   79,   79,

       79,   79,   79,   79,   81,   81,   81,   81,   81,   81,
       81,   81,   87,  325,   87,   87,   87,   87,   87,   87,
       99,   99,  324,   99,  109,  109,  253,  109,  154,  321,
      154,  320,  154,  154,  319,  154,  169,  318,  317,  169,
      169,  169,  316,  169,  170,  170,  170,  315,  170,  170,
      314,  170,  172,  172,  313,  172,  172,  172,  312,  172,
      182,  182,  311,  182,  185,  185,  310,  185,  188,  188,
      309,  188,  295,  308,  307,  295,  306,  305,  304,  301,
      300,  299,  298,  297,  296,  253,  189,  362,  362,  362,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,

      278,  277,  276,  275,  272,  271,  270,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  251,  248,  245,  362,  175,  244,  243,  235,
      234,  233,  232,  231,  230,  229,  228,  225,  222,  221,
      220,  219,  218,  217,  216,  215,  214,  213,  212,  209,
      204,  203,  202,  201,  200,  197,  196,  195,  194,  193,
      192,  180,  179,  178,  177,  176,  175,  173,  171,  150,
      149,  140,  139,  138,  137,  130,  113,  112,  111,  110,
      106,   93,   90,   89,   88,   86,   85,  362,   13,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362
    } ;

static const flex_int16_t yy_chk[661] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    7,    3,    2,    4,    5,    4,    5,
        8,    3,    5,    9,    6,    4,    6,   10,  392,    6,
       16,   16,   25,   48,   16,   28,   28,   48,   30,   35,

       35,    7,   37,   37,   47,   25,   30,   47,    8,    3,
       53,  115,   45,    4,    5,    9,   45,  115,   53,   10,
       45,    6,   31,   31,   31,   31,   32,   32,   32,   32,
       49,   46,   31,   46,   58,  391,   31,  263,   58,   31,
       46,   49,   61,   61,   31,   50,   31,   50,   32,   52,
       50,   59,   50,  263,   60,   52,   52,   60,   31,   67,
       52,   68,  124,   67,   59,   68,   31,   73,   82,   82,
      124,   73,   82,   84,   84,  100,  100,   84,  121,  121,
       73,   73,   73,   98,   98,   98,   98,  101,  101,  101,
      103,  103,  103,  103,  141,  122,   73,  100,  141,   73,

      122,  138,  390,   73,   73,   98,  138,  151,   73,  101,
      152,  151,  103,  153,  152,   73,  389,  153,   73,  236,
       73,   73,   73,  236,   73,  102,  102,  102,  102,  157,
      157,  157,  181,  181,  102,  102,  102,  174,  174,  183,
      183,  174,  184,  184,  184,  388,  216,  102,  102,  102,
      102,  102,  102,  102,  181,  186,  186,  186,  216,  237,
      387,  183,  238,  237,  184,  386,  238,  385,  190,  190,
      190,  190,  191,  191,  191,  191,  383,  186,  187,  187,
      187,  187,  239,  239,  239,  382,  381,  187,  187,  187,
      190,  246,  246,  380,  191,  379,  378,  247,  247,  358,

      187,  187,  187,  187,  187,  187,  187,  189,  189,  189,
      189,  353,  352,  246,  350,  347,  189,  189,  189,  247,
      249,  249,  249,  250,  250,  250,  293,  293,  346,  189,
      189,  189,  189,  189,  189,  189,  254,  254,  254,  254,
      345,  343,  249,  341,  340,  250,  336,  335,  293,  294,
      294,  294,  331,  330,  328,  327,  326,  324,  254,  318,
      315,  314,  313,  312,  311,  310,  308,  307,  306,  305,
      302,  294,  363,  363,  363,  363,  363,  363,  363,  363,
      364,  364,  364,  364,  364,  364,  364,  364,  365,  365,
      365,  365,  365,  365,  365,  365,  366,  366,  366,  366,

      366,  366,  366,  366,  367,  367,  367,  367,  367,  367,
      367,  367,  368,  298,  368,  368,  368,  368,  368,  368,
      369,  369,  297,  369,  370,  370,  295,  370,  371,  288,
      371,  286,  371,  371,  285,  371,  372,  284,  283,  372,
      372,  372,  282,  372,  373,  373,  373,  280,  373,  373,
      279,  373,  374,  374,  277,  374,  374,  374,  276,  374,
      375,  375,  275,  375,  376,  376,  274,  376,  377,  377,
      272,  377,  384,  271,  270,  384,  266,  265,  264,  262,
      260,  259,  258,  256,  255,  253,  252,  251,  248,  245,
      235,  234,  233,  232,  228,  227,  226,  225,  223,  222,

      221,  220,  218,  217,  214,  213,  212,  211,  210,  209,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  196,
      195,  194,  188,  185,  182,  180,  175,  173,  171,  149,
      148,  147,  146,  145,  144,  143,  142,  140,  137,  136,
      135,  133,  132,  130,  129,  128,  127,  126,  125,  123,
      120,  119,  118,  117,  116,  114,  112,  111,  110,  108,
      104,   99,   96,   91,   90,   86,   83,   80,   78,   64,
       62,   57,   56,   55,   54,   51,   44,   41,   40,   39,
       36,   26,   22,   21,   20,   18,   17,   13,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[148] =
    {   0,
0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "python.l"
#line 6 "python.l"
    #include <iostream>
    #include <string>
    #include <algorithm>
    #include <deque>
    using namespace std;

    //extern int yylineno;

    string removeUnderline(string text);
    void calculateIndentiation(int* indentStack, int* lastIndentIndex, int dentLen);
    void checkIndentiationForKeywords(deque<int>& keywordLines, int* indentStack, int lastIndentIndex, int* emptyLinesCounter, int dentLen);
#line 761 "python.flex.cpp"

#line 763 "python.flex.cpp"

#define INITIAL 0
#define INLINE_STRING_SINGLE_QUOTES 1
#define INLINE_STRING_DOUBLE_QUOTES 2
#define MULTILINE_STRING_SINGLE_QUOTES 3
#define MULTILINE_STRING_DOUBLE_QUOTES 4
#define NEW_LINE 5

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 25 "python.l"



#line 29 "python.l"
    string str;

    int lastIndentIndex = 0;
    int indentStack[1000];
    indentStack[0] = 0;

    int emptyLinesCounter = 0;

    deque<int> keywordLines = {};

    int parenthesesBracketsCounter = 0;
    int squareBracketsCounter = 0;
    int curlyBracketsCounter = 0;
    bool isString = false;


#line 1006 "python.flex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 363 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 362 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 45 "python.l"
{
    cout << "Line: " << yylineno << ". Found comment: \"" << yytext+1 << "\"" << endl;
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
YY_LINENO_REWIND_TO(yy_cp - 1);
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 49 "python.l"
{
    string text = yytext;
    emptyLinesCounter = count(text.begin(), text.end(), '\n');
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 54 "python.l"
{}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 57 "python.l"
{
    if(!(isString || parenthesesBracketsCounter || squareBracketsCounter || curlyBracketsCounter)) {
        checkIndentiationForKeywords(keywordLines, indentStack, lastIndentIndex, &emptyLinesCounter, yyleng - 1);
        calculateIndentiation(indentStack, &lastIndentIndex, yyleng - 1);
    }
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "python.l"
{
    if(!(isString || parenthesesBracketsCounter || squareBracketsCounter || curlyBracketsCounter)) {
        checkIndentiationForKeywords(keywordLines, indentStack, lastIndentIndex, &emptyLinesCounter, yyleng - 1);
        calculateIndentiation(indentStack, &lastIndentIndex, yyleng);
    }
}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 69 "python.l"
{
    if(!(isString || parenthesesBracketsCounter || squareBracketsCounter || curlyBracketsCounter)) {
        checkIndentiationForKeywords(keywordLines, indentStack, lastIndentIndex, &emptyLinesCounter, (yyleng - 1) * 4);
        calculateIndentiation(indentStack, &lastIndentIndex, (yyleng - 1) * 4);
    }
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 75 "python.l"
{
    if(!(isString || parenthesesBracketsCounter || squareBracketsCounter || curlyBracketsCounter)) {
        checkIndentiationForKeywords(keywordLines, indentStack, lastIndentIndex, &emptyLinesCounter, (yyleng - 1) * 4);
        calculateIndentiation(indentStack, &lastIndentIndex, yyleng * 4);
    }
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 81 "python.l"
{
    if(!(isString || parenthesesBracketsCounter || squareBracketsCounter || curlyBracketsCounter)) {
        cout << "Line: " << yylineno << ". ERROR: mixed tabs and spaces (dentiation)." << endl;
    }
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 87 "python.l"
{ cout << "Line: " << yylineno << ". Found arithmetical operator: " << yytext << endl; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 88 "python.l"
{ cout << "Line: " << yylineno << ". Found arithmetical operator: " << yytext << endl; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 89 "python.l"
{ cout << "Line: " << yylineno << ". Found arithmetical operator: " << yytext << endl; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 90 "python.l"
{ cout << "Line: " << yylineno << ". Found arithmetical operator: " << yytext << endl; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 91 "python.l"
{ cout << "Line: " << yylineno << ". Found arithmetical operator: " << yytext << endl; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 92 "python.l"
{ cout << "Line: " << yylineno << ". Found arithmetical operator: " << yytext << endl; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 93 "python.l"
{ cout << "Line: " << yylineno << ". Found arithmetical operator: " << yytext << endl; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 95 "python.l"
{ cout << "Line: " << yylineno << ". Found bitwise operator: " << yytext << endl; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 96 "python.l"
{ cout << "Line: " << yylineno << ". Found bitwise operator: " << yytext << endl; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 97 "python.l"
{ cout << "Line: " << yylineno << ". Found bitwise operator: " << yytext << endl; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 98 "python.l"
{ cout << "Line: " << yylineno << ". Found bitwise operator: " << yytext << endl; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 99 "python.l"
{ cout << "Line: " << yylineno << ". Found bitwise operator: " << yytext << endl; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 100 "python.l"
{ cout << "Line: " << yylineno << ". Found bitwise operator: " << yytext << endl; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 102 "python.l"
{ cout << "Line: " << yylineno << ". Found comparison operator: " << yytext << endl; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 103 "python.l"
{ cout << "Line: " << yylineno << ". Found comparison operator: " << yytext << endl; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 104 "python.l"
{ cout << "Line: " << yylineno << ". Found comparison operator: " << yytext << endl; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 105 "python.l"
{ cout << "Line: " << yylineno << ". Found comparison operator: " << yytext << endl; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 106 "python.l"
{ cout << "Line: " << yylineno << ". Found comparison operator: " << yytext << endl; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 107 "python.l"
{ cout << "Line: " << yylineno << ". Found comparison operator: " << yytext << endl; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 109 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 111 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 112 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 113 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 114 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 115 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 116 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 117 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 118 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 119 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 120 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 121 "python.l"
{ cout << "Line: " << yylineno << ". Found assignment operator: " << yytext << endl; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 123 "python.l"
{ 
        cout << "Line: " << yylineno << ". Found open parentheses bracket: " << yytext << endl;
        parenthesesBracketsCounter++; 
   }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 127 "python.l"
{ 
        cout << "Line: " << yylineno << ". Found close parentheses bracket: " << yytext << endl;
        parenthesesBracketsCounter--;
   }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 131 "python.l"
{ 
        cout << "Line: " << yylineno << ". Found open square bracket: " << yytext << endl;
        squareBracketsCounter++;
   }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 135 "python.l"
{
        cout << "Line: " << yylineno << ". Found close square bracket: " << yytext << endl;
        squareBracketsCounter--;
   }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 139 "python.l"
{ 
        cout << "Line: " << yylineno << ". Found open curly bracket: " << yytext << endl;
        curlyBracketsCounter++;
   }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 143 "python.l"
{
        cout << "Line: " << yylineno << ". Found close curly bracket: " << yytext << endl;
        curlyBracketsCounter--;
   }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 148 "python.l"
{ cout << "Line: " << yylineno << ". Found delimiter: " << yytext << endl; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 149 "python.l"
{ cout << "Line: " << yylineno << ". Found delimiter: " << yytext << endl; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 150 "python.l"
{ cout << "Line: " << yylineno << ". Found delimiter: " << yytext << endl; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 151 "python.l"
{ cout << "Line: " << yylineno << ". Found delimiter: " << yytext << endl; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 152 "python.l"
{ cout << "Line: " << yylineno << ". Found delimiter: " << yytext << endl; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 153 "python.l"
{ cout << "Line: " << yylineno << ". Found delimiter: " << yytext << endl; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 155 "python.l"
{
        cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl;
        keywordLines.push_back(yylineno);
   }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 159 "python.l"
{
        cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl;
        keywordLines.push_back(yylineno);
     }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 163 "python.l"
{
        cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl;
        keywordLines.push_back(yylineno);
     }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 167 "python.l"
{
        cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl;
        keywordLines.push_back(yylineno);
      }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 171 "python.l"
{
        cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl;
        keywordLines.push_back(yylineno);
    }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 175 "python.l"
{
        cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl;
        keywordLines.push_back(yylineno);
    }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 179 "python.l"
{
            cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl;
            keywordLines.push_back(yylineno);
       }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 183 "python.l"
{
            cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl;
            keywordLines.push_back(yylineno);
        }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 187 "python.l"
{
        cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl;
        keywordLines.push_back(yylineno);
    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 191 "python.l"
{
        cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl;
        keywordLines.push_back(yylineno);
      }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 195 "python.l"
{
        cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl;
        keywordLines.push_back(yylineno);
     }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 199 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }     
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 200 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }      
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 201 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }        
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 202 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }           
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 203 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }           
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 204 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }          
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 205 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }     
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 206 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }  
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 207 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 208 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 209 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 210 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 211 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 212 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 213 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 214 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 215 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 216 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 217 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 218 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 219 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 220 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 221 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 222 "python.l"
{ cout << "Line: " << yylineno << ". Found hard keyword: " << yytext << endl; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 224 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 225 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 226 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 227 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 228 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 229 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 230 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 231 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 232 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 233 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 234 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 235 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 236 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 237 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 238 "python.l"
{ cout << "Line: " << yylineno << ". Found data type: " << yytext << endl; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 240 "python.l"
{
    if(yyleng == 2) {
        cout << "Line: " << yylineno << ". ERROR: found empty binary literal." << endl;
    } else {
        string text = yytext;
        text = removeUnderline(text);
        cout << "Line: " << yylineno << ". Found binary literal: " << to_string(stoll(text.substr(2), NULL, 2)) << endl;
    }
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 249 "python.l"
{ cout << "Line: " << yylineno << ". ERROR: invalid binary literal (illegal use of letter)." << endl; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 250 "python.l"
{ cout << "Line: " << yylineno << ". ERROR: invalid binary literal (illegal use of underscore)." << endl; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 252 "python.l"
{
    if(yyleng == 2) {
        cout << "Line: " << yylineno << ". ERROR: found empty hexadecimal literal." << endl;
    } else {
        string text = yytext;
        text = removeUnderline(text);
        cout << "Line: " << yylineno << ". Found hexadecimal literal: " << to_string(stoll(text.substr(2), NULL, 16)) << endl;
    }
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 261 "python.l"
{ cout << "Line: " << yylineno << ". ERROR: invalid hexadecimal literal (illegal use of letter)." << endl; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 262 "python.l"
{ cout << "Line: " << yylineno << ". ERROR: invalid hexadecimal literal (illegal use of underscore)." << endl; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 264 "python.l"
{
    if(yyleng == 2) {
        cout << "Line: " << yylineno << ". ERROR: found empty octal literal." << endl;
    } else {
        string text = yytext;
        text = removeUnderline(text);
        cout << "Line: " << yylineno << ". Found octal literal: " << stoll("0" + text.substr(2), NULL, 8) << endl;
    }
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 273 "python.l"
{ cout << "Line: " << yylineno << ". ERROR: invalid octal literal (unexpected character)." << endl; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 274 "python.l"
{ cout << "Line: " << yylineno << ". ERROR: invalid octal literal (illegal use of underscore)." << endl; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 276 "python.l"
{
    string text = yytext;

    if(yyleng > 1 && text[0] == '0') {
        cout << "Line: " << yylineno << ". ERROR: invalid decimal literal (illegal use of 0)." << endl;
    } else {
        text = removeUnderline(text);
        cout << "Line: " << yylineno << ". Found decimal literal: " << text << endl;
    }
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 286 "python.l"
{ cout << "Line: " << yylineno << ". ERROR: invalid decimal literal (unexpected character)." << endl; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 287 "python.l"
{ cout << "Line: " << yylineno << ". ERROR: invalid decimal literal (illegal use of underscore)." << endl; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 289 "python.l"
{ 
    BEGIN(INLINE_STRING_SINGLE_QUOTES);
    str.clear();
    isString = true;
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 294 "python.l"
{ 
    BEGIN(INLINE_STRING_DOUBLE_QUOTES);  
    str.clear();
    isString = true;
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 299 "python.l"
{ 
    BEGIN(MULTILINE_STRING_SINGLE_QUOTES); 
    str.clear();
    isString = true;
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 304 "python.l"
{ 
    BEGIN(MULTILINE_STRING_DOUBLE_QUOTES); 
    str.clear();
    isString = true;
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 310 "python.l"
{ cout << "Line: " << yylineno << ". Found identifier: " << yytext << endl; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 312 "python.l"
{ str += yytext; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 313 "python.l"
{ str += yytext; }
	YY_BREAK
case 122:
/* rule 122 can match eol */
YY_RULE_SETUP
#line 314 "python.l"
{ str += yytext; }
	YY_BREAK
case 123:
/* rule 123 can match eol */
YY_RULE_SETUP
#line 315 "python.l"
{ str += yytext; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 317 "python.l"
{ str += "\n"; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 318 "python.l"
{ str += "\\"; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 319 "python.l"
{ str += "\'"; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 320 "python.l"
{ str += "\""; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 321 "python.l"
{ str += "\a"; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 322 "python.l"
{ str += "\b"; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 323 "python.l"
{ str += "\f"; }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 324 "python.l"
{ str += "\r"; }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 325 "python.l"
{ str += "\t"; }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 326 "python.l"
{ str += "\v"; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 327 "python.l"
{ str += (char)stoi(yytext + 1, NULL, 8); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 328 "python.l"
{ str += (char)stoi(yytext + 2, NULL, 16); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 329 "python.l"
{ str += (char)stoi(yytext + 2, NULL, 16); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 330 "python.l"
{ str += (char)stoi(yytext + 2, NULL, 16); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 331 "python.l"
{ str += "\'"; }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 332 "python.l"
{ str += "\""; }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 334 "python.l"
{
    cout << "Line: " << yylineno << ". Found inline single-quoted string literal: \'" + str + "\'" << endl;
    isString = false;
    BEGIN(INITIAL); 
}
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 339 "python.l"
{
    cout << "Line: " << yylineno << ". Found inline double-quoted string literal: \"" + str + "\"" << endl;
    isString = false;
    BEGIN(INITIAL); 
}
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 344 "python.l"
{
    cout << "Line: " << yylineno << ". Found multiline single-quoted string literal:\n\'" + str + "\'" << endl;
    isString = false;
    BEGIN(INITIAL); 
}
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 349 "python.l"
{
    cout << "Line: " << yylineno << ". Found multiline double-quoted string literal:\n\"" + str + "\"" << endl;
    isString = false;
    BEGIN(INITIAL); 
}
	YY_BREAK
case 144:
/* rule 144 can match eol */
YY_RULE_SETUP
#line 355 "python.l"
{
    int strLength = static_cast<int>(str.length());

    if(strLength > 1 && str[strLength - 1] == '\\') {
        str.erase(strLength - 1, 1);
    } else {
        cout << "Line: " << yylineno << ". ERROR: inline string literal is not closed." << endl;
        BEGIN(INITIAL);
    }
}
	YY_BREAK
case YY_STATE_EOF(INLINE_STRING_SINGLE_QUOTES):
case YY_STATE_EOF(INLINE_STRING_DOUBLE_QUOTES):
#line 365 "python.l"
{
    cout << "Line: " << yylineno << ". ERROR: inline string literal is not closed." << endl;
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(MULTILINE_STRING_SINGLE_QUOTES):
case YY_STATE_EOF(MULTILINE_STRING_DOUBLE_QUOTES):
#line 369 "python.l"
{
    cout << "Line: " << yylineno << ". ERROR: multiline string literal is not closed." << endl;
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(NEW_LINE):
#line 374 "python.l"
{ checkIndentiationForKeywords(keywordLines, indentStack, lastIndentIndex, &emptyLinesCounter, 0); return 0; }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 376 "python.l"
{}
	YY_BREAK
case 146:
/* rule 146 can match eol */
YY_RULE_SETUP
#line 378 "python.l"
{}
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 379 "python.l"
ECHO;
	YY_BREAK
#line 1992 "python.flex.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 363 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 363 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 362);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 379 "python.l"


void calculateIndentiation(int* indentStack, int* lastIndentIndex, int dentLen) {
    /* Indent */
    if(dentLen > indentStack[*lastIndentIndex]) {
        (*lastIndentIndex)++;
        indentStack[*lastIndentIndex] = dentLen;
        cout << "Line: " << yylineno << ". Found indent: " << to_string(dentLen) << endl;
    }

    /* Dedent */
    if(dentLen < indentStack[*lastIndentIndex]) {
        int tmpIndex = *lastIndentIndex;

        while(dentLen < indentStack[tmpIndex]) { tmpIndex--; }

        if(dentLen != indentStack[tmpIndex]) { cout << "Line: " << yylineno << ". ERROR: incosistent dedent: " << to_string(dentLen) << endl; }
        else {
            while(*lastIndentIndex > tmpIndex) { 
                (*lastIndentIndex)--;
                cout << "Line: " << yylineno << ". Found dedent. Indent count: " << indentStack[*lastIndentIndex] << endl; 
            }
        }  
    }
}

void checkIndentiationForKeywords(deque<int>& keywordLines, int* indentStack, int lastIndentIndex, int* emptyLinesCounter, int dentLen) {  
    if(keywordLines.empty()) {
        *emptyLinesCounter = 0;
        return;
    }

    if(yylineno - *emptyLinesCounter - keywordLines.front() != 1 || dentLen - indentStack[lastIndentIndex] <= 0) {
        cout << "Line: " << keywordLines.front() << ". ERROR: not found indent for keyword." << endl;
    }

    *emptyLinesCounter = 0;
    keywordLines.pop_front();
}

string removeUnderline(string input)
{
    string str = input;
    str.erase(remove(str.begin(), str.end(), '_'), str.end());
    return str;
}
